[container.image]
repository="ldclakmal"
name="c2c"
tag="v0.1.0"

[[container.copy.files]]
sourceFile="./resources/public.crt"
target="./resources/public.crt"

[[container.copy.files]]
sourceFile="./resources/private.key"
target="./resources/private.key"
